apiVersion: v1
kind: Service
metadata:
  name: farmer-java-service
  labels:
    app: farmer-java
spec:
  type: NodePort
  selector:
    app: farmer-java
  ports:
    - protocol: TCP
      port: 8080         # Cluster-internal port
      targetPort: 8080   # Container port in the Pod
      nodePort: 30088    # External port on the Node (you can change if needed)
